apiVersion: apps/v1
kind: Deployment
metadata:
  name: ashu-deploy
  labels:
    app: ashu-deploy-lbl
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ashu-app
  template:
    metadata:
      labels:
        app: ashu-app
    spec:
      containers:
      - name: ashu-container
        image: 95ashwini/ashu-webapp
        ports:
        - containerPort: 8080
---

